created HTML submit form for business app
Cascadia-Connections/orca-stars pull request #21
Opened 2020-04-23 20:14 UTC by MatinMirzaei

2020-04-23 20:20 UTC, edmundchan8 approved these changes
I approve

2020-04-23 21:37 UTC, SkutchWill submitted a review, later dismissed
Looks like everything we need is there.  Thank you for your hard work!

2020-04-23 22:05 UTC, edmundchan8 requested changes
Actually, just typo changed for Coordinates

2020-04-23 22:05 UTC, edmundchan8 commented on OrcaStarsWebApplication/Views/Home/bussiness_form.cshtml
>          <label>Cordinates:</label>
Rename:
```
<label>Cordinates:</label>
        <input type="text" name="Cordinates" placeholder="Cordinates">	        <input type="text" name="Cordinates" placeholder="Cordinates">
```
to
```
<label>Coordinates:</label>
        <input type="text" name="Coordinates" placeholder="Coordinates">	        <input type="text" name="Coordinates" placeholder="Coordinates">
```

2020-04-23 23:38 UTC, edmundchan8 approved these changes
Approve the changes!

2020-04-23 23:39 UTC, madelynmlocke approved these changes

2020-04-24 01:17 UTC, nateptay requested changes
Still seeing a 404 error when I ran it. It looks like the develop branch you pulled didn't have the fixes to the path yet. The current develop branch has an "Admin" view folder instead of the "Home" view folder. 
Re-naming/removing the index.cshtml page will require some changes to the Startup.cs and AdminController.cs to get to the page. 
If you could change the name of the Home view folder back to Admin that would be good, and I can make the path go to the correct page from the Controller so it can find the form page.

2020-04-24 04:10 UTC, Bansenauer-Cascadia commented
This form provides a good baseline.  It is missing an action and would be improved by including a backing ViewModel and the use of Asp tag helpers.

2020-04-24 14:59 UTC, closed without merging